/**
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.experimentautomation.dsl.generator;

import org.eclipse.xtext.xtext.generator.DefaultGeneratorModule;
import org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer;
import org.palladiosimulator.experimentautomation.dsl.generator.MyResourceSetInitializer;

@SuppressWarnings("all")
public class MyGeneratorModule extends DefaultGeneratorModule {
  public Class<? extends XtextGeneratorResourceSetInitializer> bindXtextGeneratorResourceSetInitializer() {
    return MyResourceSetInitializer.class;
  }
}
