/**
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.experimentautomation.dsl.generator;

import java.util.List;
import org.eclipse.emf.ecore.EcorePackage;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer;

@SuppressWarnings("all")
public class MyResourceSetInitializer extends XtextGeneratorResourceSetInitializer {
  @Override
  public void initialize(final ResourceSet resourceSet, final List<String> referencedResources) {
    resourceSet.getPackageRegistry().put("platform:/resource/de.uka.ipd.sdq.identifier/model/identifier.ecore", EcorePackage.eINSTANCE);
    super.initialize(resourceSet, referencedResources);
  }
}
