/*
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.experimentautomation.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractExpAutoValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage.eINSTANCE);
		return result;
	}
	
}
