/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.experimentautomation.dsl.generator

import org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer
import org.eclipse.xtext.xtext.generator.DefaultGeneratorModule

class MyGeneratorModule extends DefaultGeneratorModule {
    def Class<? extends XtextGeneratorResourceSetInitializer> bindXtextGeneratorResourceSetInitializer() {
        MyResourceSetInitializer
    }
}