/*
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.experimentautomation.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ExpAutoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/palladiosimulator/experimentautomation/dsl/parser/antlr/internal/InternalExpAuto.tokens");
	}
}
