/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Allocation Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.AllocationModel#getAllocation <em>Allocation</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getAllocationModel()
 * @model
 * @generated
 */
public interface AllocationModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Allocation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Allocation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allocation</em>' attribute.
   * @see #setAllocation(String)
   * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getAllocationModel_Allocation()
   * @model
   * @generated
   */
  String getAllocation();

  /**
   * Sets the value of the '{@link org.palladiosimulator.experimentautomation.dsl.expAuto.AllocationModel#getAllocation <em>Allocation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Allocation</em>' attribute.
   * @see #getAllocation()
   * @generated
   */
  void setAllocation(String value);

} // AllocationModel
