/**
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage
 * @generated
 */
public interface ExpAutoFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ExpAutoFactory eINSTANCE = org.palladiosimulator.experimentautomation.dsl.expAuto.impl.ExpAutoFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Datasource</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Datasource</em>'.
   * @generated
   */
  Datasource createDatasource();

  /**
   * Returns a new object of class '<em>Datasource Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Datasource Specification</em>'.
   * @generated
   */
  DatasourceSpecification createDatasourceSpecification();

  /**
   * Returns a new object of class '<em>File Datasource Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>File Datasource Specification</em>'.
   * @generated
   */
  FileDatasourceSpecification createFileDatasourceSpecification();

  /**
   * Returns a new object of class '<em>Memory Datasource Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Memory Datasource Specification</em>'.
   * @generated
   */
  MemoryDatasourceSpecification createMemoryDatasourceSpecification();

  /**
   * Returns a new object of class '<em>Experiment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Experiment</em>'.
   * @generated
   */
  Experiment createExperiment();

  /**
   * Returns a new object of class '<em>Experiment Specifications</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Experiment Specifications</em>'.
   * @generated
   */
  ExperimentSpecifications createExperimentSpecifications();

  /**
   * Returns a new object of class '<em>Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Description</em>'.
   * @generated
   */
  Description createDescription();

  /**
   * Returns a new object of class '<em>Initial Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Model</em>'.
   * @generated
   */
  InitialModel createInitialModel();

  /**
   * Returns a new object of class '<em>Init Specifications</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Init Specifications</em>'.
   * @generated
   */
  InitSpecifications createInitSpecifications();

  /**
   * Returns a new object of class '<em>Allocation Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Allocation Model</em>'.
   * @generated
   */
  AllocationModel createAllocationModel();

  /**
   * Returns a new object of class '<em>Usage Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Usage Model</em>'.
   * @generated
   */
  UsageModel createUsageModel();

  /**
   * Returns a new object of class '<em>Middleware Repository</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Middleware Repository</em>'.
   * @generated
   */
  MiddlewareRepository createMiddlewareRepository();

  /**
   * Returns a new object of class '<em>Event Middleware Repository</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Middleware Repository</em>'.
   * @generated
   */
  EventMiddlewareRepository createEventMiddlewareRepository();

  /**
   * Returns a new object of class '<em>Monitor Repository</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Monitor Repository</em>'.
   * @generated
   */
  MonitorRepository createMonitorRepository();

  /**
   * Returns a new object of class '<em>Variation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variation</em>'.
   * @generated
   */
  Variation createVariation();

  /**
   * Returns a new object of class '<em>Nested Intervals Value Provider</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nested Intervals Value Provider</em>'.
   * @generated
   */
  NestedIntervalsValueProvider createNestedIntervalsValueProvider();

  /**
   * Returns a new object of class '<em>Set Value Provider</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Value Provider</em>'.
   * @generated
   */
  SetValueProvider createSetValueProvider();

  /**
   * Returns a new object of class '<em>Linear Value Provider</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Linear Value Provider</em>'.
   * @generated
   */
  LinearValueProvider createLinearValueProvider();

  /**
   * Returns a new object of class '<em>Exponential Value Provider</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exponential Value Provider</em>'.
   * @generated
   */
  ExponentialValueProvider createExponentialValueProvider();

  /**
   * Returns a new object of class '<em>Polynomial Value Provider</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Polynomial Value Provider</em>'.
   * @generated
   */
  PolynomialValueProvider createPolynomialValueProvider();

  /**
   * Returns a new object of class '<em>Stop Time Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stop Time Condition</em>'.
   * @generated
   */
  StopTimeCondition createStopTimeCondition();

  /**
   * Returns a new object of class '<em>Stop Count Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stop Count Condition</em>'.
   * @generated
   */
  StopCountCondition createStopCountCondition();

  /**
   * Returns a new object of class '<em>Number Of Experiments</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Number Of Experiments</em>'.
   * @generated
   */
  NumberOfExperiments createNumberOfExperiments();

  /**
   * Returns a new object of class '<em>Seed Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Seed Definition</em>'.
   * @generated
   */
  SeedDefinition createSeedDefinition();

  /**
   * Returns a new object of class '<em>List Of Seeds</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Of Seeds</em>'.
   * @generated
   */
  ListOfSeeds createListOfSeeds();

  /**
   * Returns a new object of class '<em>Experiment Datasource</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Experiment Datasource</em>'.
   * @generated
   */
  ExperimentDatasource createExperimentDatasource();

  /**
   * Returns a new object of class '<em>Tool Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tool Definition</em>'.
   * @generated
   */
  ToolDefinition createToolDefinition();

  /**
   * Returns a new object of class '<em>Configuration Params</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Configuration Params</em>'.
   * @generated
   */
  ConfigurationParams createConfigurationParams();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ExpAutoPackage getExpAutoPackage();

} //ExpAutoFactory
