/**
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>File Datasource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.FileDatasource#getSourceURI <em>Source URI</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getFileDatasource()
 * @model
 * @generated
 */
public interface FileDatasource extends Datasource
{
  /**
   * Returns the value of the '<em><b>Source URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source URI</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source URI</em>' attribute.
   * @see #setSourceURI(String)
   * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getFileDatasource_SourceURI()
   * @model
   * @generated
   */
  String getSourceURI();

  /**
   * Sets the value of the '{@link org.palladiosimulator.experimentautomation.dsl.expAuto.FileDatasource#getSourceURI <em>Source URI</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source URI</em>' attribute.
   * @see #getSourceURI()
   * @generated
   */
  void setSourceURI(String value);

} // FileDatasource
