/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initial Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.InitialModel#getModeltyp <em>Modeltyp</em>}</li>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.InitialModel#getInitSpecifications <em>Init Specifications</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getInitialModel()
 * @model
 * @generated
 */
public interface InitialModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Modeltyp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Modeltyp</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modeltyp</em>' attribute.
   * @see #setModeltyp(String)
   * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getInitialModel_Modeltyp()
   * @model
   * @generated
   */
  String getModeltyp();

  /**
   * Sets the value of the '{@link org.palladiosimulator.experimentautomation.dsl.expAuto.InitialModel#getModeltyp <em>Modeltyp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modeltyp</em>' attribute.
   * @see #getModeltyp()
   * @generated
   */
  void setModeltyp(String value);

  /**
   * Returns the value of the '<em><b>Init Specifications</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init Specifications</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init Specifications</em>' containment reference.
   * @see #setInitSpecifications(InitSpecifications)
   * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getInitialModel_InitSpecifications()
   * @model containment="true"
   * @generated
   */
  InitSpecifications getInitSpecifications();

  /**
   * Sets the value of the '{@link org.palladiosimulator.experimentautomation.dsl.expAuto.InitialModel#getInitSpecifications <em>Init Specifications</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init Specifications</em>' containment reference.
   * @see #getInitSpecifications()
   * @generated
   */
  void setInitSpecifications(InitSpecifications value);

} // InitialModel
