/**
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Memory Datasource Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.MemoryDatasourceSpecification#getSourceType <em>Source Type</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getMemoryDatasourceSpecification()
 * @model
 * @generated
 */
public interface MemoryDatasourceSpecification extends EObject
{
  /**
   * Returns the value of the '<em><b>Source Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Type</em>' attribute.
   * @see #setSourceType(String)
   * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getMemoryDatasourceSpecification_SourceType()
   * @model
   * @generated
   */
  String getSourceType();

  /**
   * Sets the value of the '{@link org.palladiosimulator.experimentautomation.dsl.expAuto.MemoryDatasourceSpecification#getSourceType <em>Source Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Type</em>' attribute.
   * @see #getSourceType()
   * @generated
   */
  void setSourceType(String value);

} // MemoryDatasourceSpecification
