/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Monitor Repository</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.MonitorRepository#getMonitorRepository <em>Monitor Repository</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getMonitorRepository()
 * @model
 * @generated
 */
public interface MonitorRepository extends EObject
{
  /**
   * Returns the value of the '<em><b>Monitor Repository</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Monitor Repository</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Monitor Repository</em>' attribute.
   * @see #setMonitorRepository(String)
   * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getMonitorRepository_MonitorRepository()
   * @model
   * @generated
   */
  String getMonitorRepository();

  /**
   * Sets the value of the '{@link org.palladiosimulator.experimentautomation.dsl.expAuto.MonitorRepository#getMonitorRepository <em>Monitor Repository</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Monitor Repository</em>' attribute.
   * @see #getMonitorRepository()
   * @generated
   */
  void setMonitorRepository(String value);

} // MonitorRepository
