/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number Of Experiments</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.NumberOfExperiments#getNumberOfRepetitions <em>Number Of Repetitions</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getNumberOfExperiments()
 * @model
 * @generated
 */
public interface NumberOfExperiments extends EObject
{
  /**
   * Returns the value of the '<em><b>Number Of Repetitions</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number Of Repetitions</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number Of Repetitions</em>' attribute.
   * @see #setNumberOfRepetitions(int)
   * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getNumberOfExperiments_NumberOfRepetitions()
   * @model
   * @generated
   */
  int getNumberOfRepetitions();

  /**
   * Sets the value of the '{@link org.palladiosimulator.experimentautomation.dsl.expAuto.NumberOfExperiments#getNumberOfRepetitions <em>Number Of Repetitions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number Of Repetitions</em>' attribute.
   * @see #getNumberOfRepetitions()
   * @generated
   */
  void setNumberOfRepetitions(int value);

} // NumberOfExperiments
