/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Usage Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.UsageModel#getUsageModel <em>Usage Model</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getUsageModel()
 * @model
 * @generated
 */
public interface UsageModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Usage Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Usage Model</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Usage Model</em>' attribute.
   * @see #setUsageModel(String)
   * @see org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage#getUsageModel_UsageModel()
   * @model
   * @generated
   */
  String getUsageModel();

  /**
   * Sets the value of the '{@link org.palladiosimulator.experimentautomation.dsl.expAuto.UsageModel#getUsageModel <em>Usage Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Usage Model</em>' attribute.
   * @see #getUsageModel()
   * @generated
   */
  void setUsageModel(String value);

} // UsageModel
