/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.palladiosimulator.experimentautomation.dsl.expAuto.Datasource;
import org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage;
import org.palladiosimulator.experimentautomation.dsl.expAuto.Experiment;
import org.palladiosimulator.experimentautomation.dsl.expAuto.Import;
import org.palladiosimulator.experimentautomation.dsl.expAuto.Model;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.impl.ModelImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.impl.ModelImpl#getDatasources <em>Datasources</em>}</li>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.impl.ModelImpl#getExperiments <em>Experiments</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<Import> imports;

  /**
   * The cached value of the '{@link #getDatasources() <em>Datasources</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDatasources()
   * @generated
   * @ordered
   */
  protected EList<Datasource> datasources;

  /**
   * The cached value of the '{@link #getExperiments() <em>Experiments</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExperiments()
   * @generated
   * @ordered
   */
  protected EList<Experiment> experiments;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpAutoPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Import> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<Import>(Import.class, this, ExpAutoPackage.MODEL__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Datasource> getDatasources()
  {
    if (datasources == null)
    {
      datasources = new EObjectContainmentEList<Datasource>(Datasource.class, this, ExpAutoPackage.MODEL__DATASOURCES);
    }
    return datasources;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Experiment> getExperiments()
  {
    if (experiments == null)
    {
      experiments = new EObjectContainmentEList<Experiment>(Experiment.class, this, ExpAutoPackage.MODEL__EXPERIMENTS);
    }
    return experiments;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ExpAutoPackage.MODEL__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case ExpAutoPackage.MODEL__DATASOURCES:
        return ((InternalEList<?>)getDatasources()).basicRemove(otherEnd, msgs);
      case ExpAutoPackage.MODEL__EXPERIMENTS:
        return ((InternalEList<?>)getExperiments()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ExpAutoPackage.MODEL__IMPORTS:
        return getImports();
      case ExpAutoPackage.MODEL__DATASOURCES:
        return getDatasources();
      case ExpAutoPackage.MODEL__EXPERIMENTS:
        return getExperiments();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ExpAutoPackage.MODEL__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends Import>)newValue);
        return;
      case ExpAutoPackage.MODEL__DATASOURCES:
        getDatasources().clear();
        getDatasources().addAll((Collection<? extends Datasource>)newValue);
        return;
      case ExpAutoPackage.MODEL__EXPERIMENTS:
        getExperiments().clear();
        getExperiments().addAll((Collection<? extends Experiment>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ExpAutoPackage.MODEL__IMPORTS:
        getImports().clear();
        return;
      case ExpAutoPackage.MODEL__DATASOURCES:
        getDatasources().clear();
        return;
      case ExpAutoPackage.MODEL__EXPERIMENTS:
        getExperiments().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ExpAutoPackage.MODEL__IMPORTS:
        return imports != null && !imports.isEmpty();
      case ExpAutoPackage.MODEL__DATASOURCES:
        return datasources != null && !datasources.isEmpty();
      case ExpAutoPackage.MODEL__EXPERIMENTS:
        return experiments != null && !experiments.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
