/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.experimentautomation.dsl.expAuto.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.palladiosimulator.experimentautomation.dsl.expAuto.ConfigurationParams;
import org.palladiosimulator.experimentautomation.dsl.expAuto.ExpAutoPackage;
import org.palladiosimulator.experimentautomation.dsl.expAuto.ToolDefinition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tool Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.impl.ToolDefinitionImpl#getTool <em>Tool</em>}</li>
 *   <li>{@link org.palladiosimulator.experimentautomation.dsl.expAuto.impl.ToolDefinitionImpl#getConfigParams <em>Config Params</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ToolDefinitionImpl extends MinimalEObjectImpl.Container implements ToolDefinition
{
  /**
   * The default value of the '{@link #getTool() <em>Tool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTool()
   * @generated
   * @ordered
   */
  protected static final String TOOL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTool() <em>Tool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTool()
   * @generated
   * @ordered
   */
  protected String tool = TOOL_EDEFAULT;

  /**
   * The cached value of the '{@link #getConfigParams() <em>Config Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConfigParams()
   * @generated
   * @ordered
   */
  protected EList<ConfigurationParams> configParams;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ToolDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpAutoPackage.Literals.TOOL_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTool()
  {
    return tool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTool(String newTool)
  {
    String oldTool = tool;
    tool = newTool;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ExpAutoPackage.TOOL_DEFINITION__TOOL, oldTool, tool));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ConfigurationParams> getConfigParams()
  {
    if (configParams == null)
    {
      configParams = new EObjectContainmentEList<ConfigurationParams>(ConfigurationParams.class, this, ExpAutoPackage.TOOL_DEFINITION__CONFIG_PARAMS);
    }
    return configParams;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ExpAutoPackage.TOOL_DEFINITION__CONFIG_PARAMS:
        return ((InternalEList<?>)getConfigParams()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ExpAutoPackage.TOOL_DEFINITION__TOOL:
        return getTool();
      case ExpAutoPackage.TOOL_DEFINITION__CONFIG_PARAMS:
        return getConfigParams();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ExpAutoPackage.TOOL_DEFINITION__TOOL:
        setTool((String)newValue);
        return;
      case ExpAutoPackage.TOOL_DEFINITION__CONFIG_PARAMS:
        getConfigParams().clear();
        getConfigParams().addAll((Collection<? extends ConfigurationParams>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ExpAutoPackage.TOOL_DEFINITION__TOOL:
        setTool(TOOL_EDEFAULT);
        return;
      case ExpAutoPackage.TOOL_DEFINITION__CONFIG_PARAMS:
        getConfigParams().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ExpAutoPackage.TOOL_DEFINITION__TOOL:
        return TOOL_EDEFAULT == null ? tool != null : !TOOL_EDEFAULT.equals(tool);
      case ExpAutoPackage.TOOL_DEFINITION__CONFIG_PARAMS:
        return configParams != null && !configParams.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (tool: ");
    result.append(tool);
    result.append(')');
    return result.toString();
  }

} //ToolDefinitionImpl
